---
name: codecov
on:
  push:
    branches:
      - master
jobs:
  codecov:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0
      - run: bundle update
      - run: bundle exec rake
      - uses: codecov/codecov-action@v3
        with:
          file: coverage/.resultset.json
          fail_ci_if_error: true
