---
name: codecov
on:
  push:
    branches:
      - master
jobs:
  codecov:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0
      - run: bundle update
      - run: bundle exec rake
      - uses: codecov/codecov-action@v4
        with:
          file: coverage/.resultset.json
          fail_ci_if_error: true
